### ISSUE TITLE
NullPointerException: ssl_session == null

### ISSUE THREAD

**Issue by OJIer3** [AdmitadSDK/android_sdk#10]
v1.5.2

Caused by java.lang.NullPointerException: ssl_session == null
       at com.android.org.conscrypt.NativeCrypto.SSL_SESSION_cipher(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSessionImpl.getCipherSuite(OpenSSLSessionImpl.java:320)
       at com.android.okhttp.Handshake.get(Handshake.java:48)
       at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:105)
       at com.android.okhttp.Connection.connect(Connection.java:167)
       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209)
       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
       at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:354)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:343)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:261)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:454)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
       at ru.tachos.admitadstatisticsdk.NetworkRepositoryImpl.isServerAvailable(NetworkRepositoryImpl.java:128)
       at ru.tachos.admitadstatisticsdk.TrackerControllerImpl$InitializationAsynctask.doInBackground(TrackerControllerImpl.java:329)
       at ru.tachos.admitadstatisticsdk.TrackerControllerImpl$InitializationAsynctask.doInBackground(TrackerControllerImpl.java:316)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by admitad-github** [comment]
it's a bug from google code, can be fixed only by device vendor or google https://github.com/square/okhttp/issues/3529#issuecomment-348415095
