### ISSUE TITLE
Gradle build execution failed when I have a play-services with version above 11.6.2

### ISSUE THREAD

**Issue by serhiiwinl** [AdmitadSDK/android_sdk#12]
dependencies of your sdk
ru.tachos.admitadstatisticsdk:admitadstatisticsdk:1.6.5
     +--- com.google.android.gms:play-services-ads:11.6.2
     |    +--- com.google.android.gms:play-services-ads-lite:11.6.2
     |    |    +--- com.google.android.gms:play-services-basement:11.6.2 -> 16.2.0 (*)
     |    |    \--- com.google.android.gms:play-services-ads-lite-license:11.6.2
     |    +--- com.google.android.gms:play-services-basement:11.6.2 -> 16.2.0 (*)
     |    +--- com.google.android.gms:play-services-gass:11.6.2
     |    |    +--- com.google.android.gms:play-services-basement:11.6.2 -> 16.2.0 (*)
     |    |    \--- com.google.android.gms:play-services-gass-license:11.6.2
     |    \--- com.google.android.gms:play-services-ads-license:11.6.2
     \--- com.squareup.okhttp3:okhttp:3.9.1
          \--- com.squareup.okio:okio:1.13.0
**I can't use it with actual version of google play-services**

test project dependencies 
**implementation 'ru.tachos.admitadstatisticsdk:admitadstatisticsdk:1.6.5'
implementation 'androidx.appcompat:appcompat:1.0.2'
implementation 'com.google.firebase:firebase-core:17.0.1'**

com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process ~.gradle\caches\transforms-1\files-1.1\jetified-play-services-ads-11.6.2.aar\12ca0050a61ecae9da88957c4d835c00\jars\classes.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by ATchernov** [comment]
I have this too

**Comment by RenshawPeng** [comment]
I have this too too

**Comment by ATchernov** [comment]
> I have this too too

I found that project, that was fixed by setting constraints for dependencies in build.gradle:
```
    constraints {
        implementation ('com.google.android.gms:play-services-wallet:16.0.0') {

        }
        implementation ('com.google.android.gms:play-services-ads:16.0.0') {

        }
        implementation ('com.google.android.gms:play-services-gass:16.0.0') {

        }
    }
```

**Comment by RenshawPeng** [comment]
> > I have this too too
> 
> I found that project, that was fixed by setting constraints for dependencies in build.gradle:
> 
> ```
>     constraints {
>         implementation ('com.google.android.gms:play-services-wallet:16.0.0') {
> 
>         }
>         implementation ('com.google.android.gms:play-services-ads:16.0.0') {
> 
>         }
>         implementation ('com.google.android.gms:play-services-gass:16.0.0') {
> 
>         }
>     }
> ```

this my code，i  don't ads
```
    implementation ('ru.tachos.admitadstatisticsdk:admitadstatisticsdk:1.6.5'){
        exclude group: 'com.google.android.gms'
    }

```
