### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked

### ISSUE THREAD

**Issue by OJIer3** [AdmitadSDK/android_sdk#7]
v1.5.2
2k crashes in first day after update application with Admitad integrated. Stack trace from crashlytics

Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:641)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:323)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:297)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:579)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       **at ru.tachos.admitadstatisticsdk.DatabaseRepositorySQLite.findAll(DatabaseRepositorySQLite.java:70)
       at ru.tachos.admitadstatisticsdk.TrackerControllerImpl$InitializationAsynctask.doInBackground(TrackerControllerImpl.java:330)
       at ru.tachos.admitadstatisticsdk.TrackerControllerImpl$InitializationAsynctask.doInBackground(TrackerControllerImpl.java:316**
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by admitad-github** [comment]
Could you provide steps to reproduce?

**Comment by mitisimus** [comment]
We couldn't reproduce your bug in lots of test, but added an extra check just to be sure 
https://github.com/AdmitadSDK/android_sdk/commit/7f2ea2d84907cbbfca9c5d3d31b093c703268e81

**Comment by admitad-github** [comment]
We couldn't repoduce your bug in lots of tests. But added extra checking to be sure
https://github.com/AdmitadSDK/android_sdk/commit/7f2ea2d84907cbbfca9c5d3d31b093c703268e81
