### ISSUE TITLE
android.database.sqlite.SQLiteException: table AdmitadEvent already exists (code 1)

### ISSUE THREAD

**Issue by OJIer3** [AdmitadSDK/android_sdk#8]
v1.5.2

Caused by android.database.sqlite.SQLiteException: table AdmitadEvent already exists (code 1)
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(table AdmitadEvent already exists (code 1))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:816)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2071)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2000)
       at ru.tachos.admitadstatisticsdk.TrackerDatabaseHelper.onCreate(TrackerDatabaseHelper.java:25)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at ru.tachos.admitadstatisticsdk.DatabaseRepositorySQLite.findAll(DatabaseRepositorySQLite.java:70)
       at ru.tachos.admitadstatisticsdk.TrackerControllerImpl$InitializationAsynctask.doInBackground(TrackerControllerImpl.java:330)
       at ru.tachos.admitadstatisticsdk.TrackerControllerImpl$InitializationAsynctask.doInBackground(TrackerControllerImpl.java:316)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by admitad-github** [comment]
https://github.com/AdmitadSDK/android_sdk/commit/7f2ea2d84907cbbfca9c5d3d31b093c703268e81
