### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked (DatabaseRepositorySQLite.java) 

### ISSUE THREAD

**Issue by OJIer3** [AdmitadSDK/android_sdk#9]
v1.5.2

Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:563)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:506)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:417)
       **at ru.tachos.admitadstatisticsdk.DatabaseRepositorySQLite$1.run(DatabaseRepositorySQLite.java:43)**
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:562)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:522)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:430)
      **at ru.tachos.admitadstatisticsdk.DatabaseRepositorySQLite$2.run(DatabaseRepositorySQLite.java:58)**
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by admitad-github** [comment]
Could you please provide information about your environment and steps to reproduce?

**Comment by OJIer3** [comment]
This happens if initialize Admitad sdk in Application.onCreate() method if there is any other application component runing in another process (service for example). We moved initialization code in Activity.onCreate() method and problem was gone.

**Comment by admitad-github** [comment]
We tried to create new Application with Activity and registered Service. We initialized AdmitadTracker in Application.onCreate and used it in Activity while Service was running.
This scenario didn't reproduce your issue.

Please provide more detailed instructions or give us sample project.

**Comment by OJIer3** [comment]
Service should be run in separate process e.g. has android:process=":some_process" in manifest. This happens on v 1.5.2 but according to https://github.com/AdmitadSDK/android_sdk/issues/7 you add some checks already.

**Comment by admitad-github** [comment]
Thank you. We couldn't reproduce the issue while launching service in a separate process.
Please open new issue if this problem will return.
